site_name: OPC UA Agent
site_url: https://opcua-agent.readthedocs.org
repo_url: https://github.com/Engineering-Research-and-Development/iotagent-opcua
site_description: OPC UA Agent Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css:
  [
    "https://www.fiware.org/style/fiware_readthedocs.css",
    "https://www.fiware.org/style/fiware_readthedocs_iot.css",
  ]
google_analytics: ["UA-118589264-1", "opcua-agent.readthedocs.io"]
pages:
  - "Home - Getting Started": "index.md"
  - "Tutorial": "opc_ua_agent_tutorial.md"
  - "User & Programmers Manual": "user_and_programmers_manual.md"
  - "Installation & Administration Manual": "installation_and_administration_guide.md"
