version: "2.3"
services:

   iotage:
      hostname: iotage
      image: rdlabengpa/opcuaage:latest
      networks:
         - hostnet
         - iotnet
      ports:
         - "4001:4001"
         - "4081:8080"
      depends_on:
         - iotmongo
      volumes:
         - ./AGECONF:/opt/iotagent-opcua/conf

   iotmongo:
      hostname: iotmongo
      image: mongo:3.4
      networks:
         - iotnet
      volumes:
         - iotmongo_data:/data/db
         - iotmongo_conf:/data/configdb

volumes:
       iotmongo_data:
       iotmongo_conf:

networks:
       hostnet:
       iotnet:
