#!/bin/bash
#
# Copyright 2020 Engineering Ingegneria Informatica S.p.A.
#
docker image build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	-t $IMAGE_NAME \
	.